import click
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_preventivo(cliente: str, dest: str, verbose: bool = False):
    """
    Genera un file PDF di preventivo per un dato cliente.

    :param cliente: nome del cliente
    :param dest: percorso di destinazione del PDF
    :param verbose: se True, mostra log dettagliati
    """
    if verbose:
        click.echo(f"[DEBUG] Inizio generazione PDF per: {cliente}")
        click.echo(f"[DEBUG] Salvataggio su: {dest}")

    # Imposta il documento PDF
    c = canvas.Canvas(dest, pagesize=A4)
    width, height = A4

    # Titolo
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, f"Preventivo per: {cliente}")

    # Corpo del preventivo (placeholder)
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 100, "Dettagli del preventivo:")
    c.drawString(70, height - 120, "- Servizio A: €100")
    c.drawString(70, height - 140, "- Servizio B: €200")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 30, "Generated by Preventivi Cyberworks")

    # Salva PDF
    c.showPage()
    c.save()

    if verbose:
        click.echo("[DEBUG] PDF generato con successo.")
